src/Entity/Review.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Mime\Message;
use App\Repository\ReviewRepository;

/**
 * @ORM\Entity(repositoryClass=ReviewRepository::class)
 */
class Review
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\PositiveOrZero(message="Votre note doit être au dessus de 0")
     */
    private $note;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reviews")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="reviews")
     */
    private $product;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(?int $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 *  @UniqueEntity(
 * fields ={"email"},
 * message="Email déjà utilisé , connectez vous !"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Type("string")(
     *     message = "Ce champ ne peut contenir des caractère numeriques")
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Type("string")(
     *     message = "Ce champ ne peut contenir des caractère numeriques")
     */

    private $firstname;

    /**
     * @ORM\Column(type="string", length=255 )
     * @Assert\Email(
     *     message = "L'email '{{ value }}' n'est pas une adresse mail valide.")
     */
    private $email;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $inscriptionDate;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="4" , minMessage="Votre mot de passe doit faire au minimum 4 caractères")
    
     */
    private $password;

    /** 
    * @Assert\EqualTo(propertyPath="password" , message="Mot de passe differents")
    */
    private $confirm_password;


    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resetToken;

    /**
     * @ORM\OneToMany(targetEntity=PurchaseOrder::class, mappedBy="user", orphanRemoval=true)
     */
    private $purchaseOrders;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="user" , orphanRemoval=true)
     */
    private $reviews;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $activation_token;

    public function __construct()
    {
        $this->purchaseOrders = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstname;
    }

    public function setFirstName(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getInscriptionDate(): ?\DateTimeInterface
    {
        return $this->inscriptionDate;
    }

    public function setInscriptionDate(?\DateTimeInterface $inscriptionDate): self
    {
        $this->inscriptionDate = $inscriptionDate;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getConfirmPassword(): ?string
    {
        return $this->confirm_password;
    }

    public function setConfirmPassword(string $confirm_password): self
    {
        $this->confirm_password = $confirm_password;

        return $this;
    }

    public function __toString()
    {
        return $this->getName()." ".$this->getFirstName();
    }

    /**
     * @return Collection|PurchaseOrder[]
     */
    public function getPurchaseOrders(): Collection
    {
        return $this->purchaseOrders;
    }

    public function addPurchaseOrder(PurchaseOrder $purchaseOrder): self
    {
        if (!$this->purchaseOrders->contains($purchaseOrder)) {
            $this->purchaseOrders[] = $purchaseOrder;
            $purchaseOrder->setUser($this);
        }

        return $this;
    }

    public function removePurchaseOrder(PurchaseOrder $purchaseOrder): self
    {
        if ($this->purchaseOrders->contains($purchaseOrder)) {
            $this->purchaseOrders->removeElement($purchaseOrder);
            // set the owning side to null (unless already changed)
            if ($purchaseOrder->getUser() === $this) {
                $purchaseOrder->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setUser($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->contains($review)) {
            $this->reviews->removeElement($review);
            // set the owning side to null (unless already changed)
            if ($review->getUser() === $this) {
                $review->setUser(null);
            }
        }

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    // ...
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_ANONYMOUS
        $roles[] = 'ROLE_ANONYMOUS';
                   'ROLE_USER';
                   'ROLE_ADMIN';

        return array_unique($roles);
    }

        /**
         * Set the value of roles
         *
         * @return  self
         */ 
        public function setRoles($roles)
        {
                $this->roles = $roles;

                return $this;
        }

        public function getUsername(): ?string
        {
            return $this->roles[0];
        }
    
        public function setUsername(array $roles): self
        {
            $this->roles = $roles;
    
            return $this;
        }

  public function getSalt()
  {
      
  }
  public function eraseCredentials()
  {

  }

  public function getActivationToken(): ?string
  {
      return $this->activation_token;
  }

  public function setActivationToken(?string $activation_token): self
  {
      $this->activation_token = $activation_token;

      return $this;
  }

  public function getPlainPassword(): ?string
  {
      return $this->password;
  }

  public function setPlainPassword(?string $password): self
  {
      $this->$password = $password;

      return $this;
  }
  
}

templates/security/activation_confirmed.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div style="text-align:center; margin-top: 15em;">
<h1>Merci ! Votre compte a bien été activé !</h1>

<p><a href="{{ path('security_login') }}">Connectez vous</a> pour avoir accès à toutes les fonctionnalités du site </p>
</div>
{% endblock %}

templates/security/edit_password.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1>Modifier mon mot de passe</h1>

{{ form(form) }}


{% endblock %}

templates/security/forgotten_password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mot de passe oublié{% endblock %}

{% block body %}
    <h1>Mot de passe oublié</h1>
    {{ form(emailForm) }}
{% endblock %}

templates/security/login.html.twig
{% extends 'base_without_search.html.twig' %}

{% block body %}
	<style>
		h3 {
			font-size: 0.85rem;
			text-transform: uppercase;
			color: #ccc
		}
		label {
			font-size: 0.85rem;
			text-transform: uppercase;
			color: #ccc;
		}
	</style>
	<div id="formulaire_connexion">
	<h1>Connexion</h1>
	{# <br> #}

	{# <form action="{{ path('security_login') }}" method="POST">
						{% if error %}
							<div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security', 'fr') }}</div>
						{% endif %}
						<h3>Adresse email</h3>
			
			
						<div class="form-groupe">
			
							<input placeholder="Adresse email..." required name="_username" type="email" class="form-control">
							<br></div>
			
						<h3>Mot de passe</h3>
						<div class="form-groupe">
							<input placeholder="Mot de passe..." required name="_password" type="password" class="form-control">
							<br></div>
			
						<input type="checkbox" id="remember_me" name="_remember_me" checked/>
						<label for="remember_me">Se souvenir de moi</label>
			
						<div class="form-groupe">
							<button type="submit" class="btn btn-success">Connexion !</button>
						</div>
					</form>
			
					<div>
						<a href="{{ path('forgotten_password') }}">Mot de passe oublié ?</a>
					</div>
				</div> #}

	<div class="login__container">
		<div class="container__child signup__thumbnail">
			<div class="thumbnail__content text-center" style="margin: 0 0 auto;">
				<h1 class="heading--primary">Heureux de vous revoir !</h1>
				<h2 class="heading--secondary">Notre site n'est pas pareil sans vous!</h2>
			</div>
		</div>
		<div class="container__child signup__form" style=" text-align: center; padding: 7em;">
			<form action="{{ path('security_login') }}" method="POST">
				{% if error %}
					<div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security', 'fr') }}</div>
				{% endif %}
				<h3>Adresse email</h3>


				<div class="form-groupe">

					<input placeholder="Adresse email..." required name="_username" type="email" class="form-control form-input">
					<br></div>

				<h3>Mot de passe</h3>
				<div class="form-groupe">
					<input id="password" placeholder="Mot de passe..." required name="_password" type="password" class="form-control form-input">
					<div style="display:flex;">  <label for="checkbox">
					<input type="checkbox" id="checkbox"> Afficher le mot de passe
   					</label> </div>
					<br></div>

				<input type="checkbox" id="remember_me" name="_remember_me" checked/>
				<label for="remember_me">Se souvenir de moi</label>

				<div class="form-groupe">
					<button type="submit" class="btn--form-registration" style=" margin-bottom: 2em;margin-top: 2em;">Connexion !</button>
				</div>
				<div class="form-groupe" style="display: flex; justify-content: space-evenly;">
					<a class="signup__link" href="{{ path('security_registration') }}">Nouveau sur le site ?</a>
					<a class="signup__link" href="{{ path('forgotten_password') }}">Mot de passe oublié?</a>
				</div>
			</form>
		</div>
	</div>
</div>

{% block javascript %}
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="js/login.js"> </script>
{% endblock %}
{% endblock %}

templates/security/profil.html.twig
{% extends 'base.html.twig' %}


{% block body %}


	<h1>Bienvenue sur votre compte
		{{app.user.name  }}</h1>

 {{ form_start(form) }}

<div class="row">
	<div class="col">
		<div class="alert alert-light">
			<h2 class="alert-heading">Informations générales</h2>
			<hr>
			{{ form_row(form.firstname) }}
			{{ form_row(form.name) }}
			{% if ( app.user.activationToken is not null)  and (app.user and is_granted('ROLE_ANONYMOUS'))  %}
			{{ form_row(form.email) }} 
			<div class="alert alert-danger" role="alert"><em>Votre email n'est pas activé si vous souhaitez renvoyer un mail <a href="{{ path('security_mail_token') }}">cliquez ici </em> <i style ="color: red;" class="fas fa-exclamation-triangle"></i>
			{% else %}
				{{ form_row(form.email) }} 
			{% endif %}
		</div>
	</div>
	<div class="col">
		<div class="alert alert-light">
			<h2 class="alert-heading">Détails</h2>
			<hr>
			<a href="{{path('edit_password' )}}">Modifier votre mot de passe</a>
		</br>
	</br>
	<a style="color:red;"href="{{path('delete_user' ,{id: app.user.id })}}">Supprimer mon compte</a> <i style ="color: red;" class="fas fa-exclamation-triangle"></i>
<br><br>
	{# <a href="{{path('purchase_list')}}">Mon Historique de commande</a> #}

	<hr>
	<p>Si vous avez terminé vos modifications, vous pouvez les sauvegarder</p>
	<button type="submit" class="btn btn-primary">
		<i class="fas fa-check"></i>
		Enregistrer les modifications
	</button>
</div></div></div>{{ form_end(form) }}</div>{% endblock %} 

templates/security/purchase_list.html.twig
{% extends 'base_without_search.html.twig' %}

{% block body %}
<style> .sortable {
	color: #900000;
}
</style>
<h1 style= "text-align: center;
margin-top: 1.5em;">Historique des commandes</h1>
	{% if user.purchaseOrders | length > 0 %}
		<table class="table" style="border: 2px solid; width: 95%; margin: auto; margin-top: 5em;">
			<thead class="thead-dark">
				<tr>

					<th scope="col">N° de la commande</th>
					<th scope="col">{{ knp_pagination_sortable(purchaseOrders, 'Date de la commande' , 'po.createdAt') }}</th>
					<th scope="col">Total</th>
					<th scope="col">Contenu de la commande</th>
					<th scope="col">PDF de la commande</th>


				</tr>
			</thead>
			<tbody>
				{% for purchaseOrder in user.purchaseOrders %}

					<tr>
						<td scope="row">{{purchaseOrder.id}}</td>
						<td scope="row">{{purchaseOrder.createdAt | date('d/m/Y')}}</td>
						<td scope="row">{{purchaseOrder.total}}
							€</td>
						{% set recaps =  purchaseOrder.purchaseOrderProducts %}

						{% for recap in recaps %}{% endfor %}
						<td scope="row">
							{% for recap in recaps %}
								<a href="{{ path('product_show', {'id':recap.products.id}) }}">{{recap.products.label}}
									x
									{{recap.qty}}</a>
							{% endfor %}
						</td>

						<td scope="row">
							<a class="btn-floating btn-blue-grey" href="{{ path('purchase_pdf' , {'id':purchaseOrder.id}) }}">
								<i class="fas  fa-arrow-alt-circle-down" style="color: #900000"></i>
							</a>
						</td>

					</tr>
				{% endfor %}

			</tbody>
		</table>
		{{ knp_pagination_render(purchaseOrders) }}


	{% else %}
		<p style="font-size: 30px; margin-top: 5em; text-align: center;">Vous n'avez pas encore de commande chez nous :(</p>
	{% endif %}
{% endblock %}

templates/security/registration.html.twig
{% extends 'base_without_search.html.twig' %}

{% block body %}
	<style>
		label {
			font-size: 0.85rem;
			text-transform: uppercase;
			color: #ccc;
		}
	</style>
	<div id="formulaire_inscription">
		<h1>Inscription</h1>


		{# {{ form_row(form.name , {'label' : 'Nom' ,'attr': {'placeholder': 'Nom'}} )}}
								{{ form_row(form.firstname , {'label' : 'Prénom' ,'attr': {'placeholder': 'Prénom'}})}}
								{{ form_row(form.email , {'label' : 'Adresse mail' ,'attr': {'placeholder': 'Adresse mail'}})}}
								{{ form_row(form.password , {'label' : 'Mot de passe' ,'attr': {'placeholder': 'Mot de passe'}})}}
								{{ form_row(form.confirm_password , {'label' : 'Verification du Mot de passe' ,'attr': {'placeholder': 'Répétez votre mot de passe'}})}}  #}

		<div class="signup__container">
			<div
				class="container__child signup__thumbnail">
				{# <div class="thumbnail__logo">
																	<h1 class="logo__text">Inscription</h1>
																</div> #}
				<div class="thumbnail__content text-center" style="margin: 0 0 auto;">
					<h1 class="heading--primary">Bienvenue sur GAMEIFY !</h1>
					<h2 class="heading--secondary">Le monde GEEK à portée de main</h2>
				</div>
			</div>
			<div class="container__child signup__form">
				<div class="form-group">
					{{ form_start(form) }}
					{# <label for="username">Username</label> #}
					{{ form_row(form.name , {'label' : 'Nom' ,'attr': {'placeholder': 'Nom' , 'class' : 'form-input'}}
					)}}
				</div>
				<div
					class="form-group">
					{# <label for="email">Email</label> #}
					{{ form_row(form.firstname , {'label' : 'Prénom' ,'attr': {'placeholder': 'Prénom' , 'class' : 'form-input'}})}}
				</div>
				<div
					class="form-group">
					{# <label for="password">Password</label> #}
					{{ form_row(form.email , {'label' : 'Adresse mail' ,'attr': {'placeholder': 'Adresse mail' , 'class' : 'form-input'} })}}
				</div>
				<div
					class="form-group">
					{# <label for="passwordRepeat">Repeat Password</label> #}
					{{ form_row(form.password , {'label' : 'Mot de passe' ,'attr': {'placeholder': 'Mot de passe' , 'class' : 'form-input' , 'id' : 'password'}})}}
					<div
						class="form-group">
						{# <label for="passwordRepeat">Repeat Password</label> #}
						{{ form_row(form.confirm_password , {'label' : 'Verification du Mot de passe' ,'attr': {'placeholder': 'Répétez votre mot de passe' , 'class' : 'form-input' , 'id' : 'password'}})}}
						<div>
							<label for="checkbox"><input type="checkbox" id="checkbox">
								Afficher le mot de passe
							</label>
						</div>
					</div>
				</div>
				<div class="m-t-lg">
					<ul class="list-inline">
						<li>
							{# <input class="btn btn--form" type="submit" value="Insciption" /> #}
							<button type="submit" class="btn--form-registration" style=" margin-bottom: 2em;margin-top: 2em;">
								Inscription
							</button>
							{{form_end(form)}}
						</li>
						<li>
							<a class="signup__link" href="{{ path('security_login') }}">J'ai déjà un compte</a>
						</li>
					</ul>
				</div>
			</div>
		</div>

	</div>

	{% block javascript %}
		<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
		<script src="js/registration.js"></script>
	{% endblock %}
{% endblock %}

templates/security/reset_password.html.twig
{% extends 'base.html.twig' %}
 
{% block title %}Nouveau mot de passe{% endblock %}
 
{% block body %}
<h1>Réinitialisation du mot de passe</h1>
<p>Veuillez entrer votre nouveau mot de passe ci-dessous.</p>
<form method="post">
    <label for="inputPassword">Password</label>
    <input type="password" name="password" id="inputPassword" placeholder="Mot de passe" required>
    <input type="hidden" name="token" value="{{ token }}">
    <button type="submit" id="valider">
        Valider le mot de passe
    </button>   
</form>
{% endblock %}