src/Entity/Product.php
<?php

namespace App\Entity;

use App\Entity\User;
use App\Entity\Review;
use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     */
    private $releaseDate;

    /**
     * @ORM\Column(type="integer")
     */
    private $stock;

    /**
     * @ORM\Column(type="float")
     */
    private $price;


    /**
     * @ORM\Column(type="boolean")
     */
    private $new;

   
    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="product", cascade={"remove"})
     */
    private $reviews;

    /**
     * @ORM\ManyToMany(targetEntity=Genre::class, inversedBy="products")
     */
    private $genres;

    /**
     * @ORM\ManyToMany(targetEntity=Platform::class, mappedBy="products")
     */
    private $platforms;

    /**
     * @ORM\ManyToOne(targetEntity=Conceptor::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $conceptor;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity=Picture::class, mappedBy="product" ,
     * orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @ORM\OneToMany(targetEntity=PurchaseOrderProduct::class, mappedBy="products")
     */
    private $purchaseOrderProducts;

   
   
    /**
     * Permet de récupérer le commentaire d'un auteur par rapport à une annonce
     *
     * @param User $user
     * @return Review|null
     */
    public function getReviewsFromAuthor(User $user){

        // $user = $this->getReviews()->getUser();
        foreach($this->reviews as $review) {
            if($review->getUser() === $user) return $review;

            // else{
            //     return $this->getReviews();
            // }
        }

        return null;
    }


     /**
     * Permet de récupérer le commentaire d'un auteur par rapport à une annonce
     *
     * @param User $user
     * @return PurchaseOrderProduct|null
     */
    public function getPurchaseFromAuthor(User $user){

        // $user = $this->getReviews()->getUser();
        foreach($this->purchaseOrderProducts as $pop) {
            if($pop->getPurchaseOrders()->getUser() === $user) return $pop;

            // else{
            //     return $this->getReviews();
            // }
        }

        return null;
    }

    /**
     * Permet d'obtenir la moyenne globale des notes pour cette annonce
     *
     * @return float
     */
    public function getAvgNote() {
        // Calculer la somme des notations
        $sum = array_reduce($this->reviews->toArray(), function($total, $review) {
            return $total + $review->getNote();
        }, 0);

        // Faire la division pour avoir la moyenne
        if(count($this->reviews) > 0) return $sum / count($this->reviews);

        return 0;
    }

    
   

    public function __construct()
    {
        $this->carts = new ArrayCollection();
        $this->reviews = new ArrayCollection();
        $this->genres = new ArrayCollection();
        $this->platforms = new ArrayCollection();
        $this->pictures = new ArrayCollection();
        $this->purchaseOrderProducts = new ArrayCollection();

    }

    
    public function __toString()
    {
        return $this->label;
    }




    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->releaseDate;
    }

    public function setReleaseDate(\DateTimeInterface $releaseDate): self
    {
        $this->releaseDate = $releaseDate;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }



    public function getNew(): ?bool
    {
        return $this->new;
    }

    public function setNew(bool $new): self
    {
        $this->new = $new;

        return $this;
    }



    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setProduct($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->contains($review)) {
            $this->reviews->removeElement($review);
            // set the owning side to null (unless already changed)
            if ($review->getProduct() === $this) {
                $review->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        if ($this->genres->contains($genre)) {
            $this->genres->removeElement($genre);
        }

        return $this;
    }

    /**
     * @return Collection|Platform[]
     */
    public function getPlatforms(): Collection
    {
        return $this->platforms;
    }

    public function addPlatform(Platform $platform): self
    {
        if (!$this->platforms->contains($platform)) {
            $this->platforms[] = $platform;
            $platform->addProduct($this);
        }

        return $this;
    }

    public function removePlatform(Platform $platform): self
    {
        if ($this->platforms->contains($platform)) {
            $this->platforms->removeElement($platform);
            $platform->removeProduct($this);
        }

        return $this;
    }

    public function getConceptor(): ?Conceptor
    {
        return $this->conceptor;
    }

    public function setConceptor(?Conceptor $conceptor): self
    {
        $this->conceptor = $conceptor;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setProduct($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getProduct() === $this) {
                $picture->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|PurchaseOrderProduct[]
     */
    public function getPurchaseOrderProducts(): Collection
    {
        return $this->purchaseOrderProducts;
    }

    public function addPurchaseOrderProduct(PurchaseOrderProduct $purchaseOrderProduct): self
    {
        if (!$this->purchaseOrderProducts->contains($purchaseOrderProduct)) {
            $this->purchaseOrderProducts[] = $purchaseOrderProduct;
            $purchaseOrderProduct->setProducts($this);
        }

        return $this;
    }

    public function removePurchaseOrderProduct(PurchaseOrderProduct $purchaseOrderProduct): self
    {
        if ($this->purchaseOrderProducts->contains($purchaseOrderProduct)) {
            $this->purchaseOrderProducts->removeElement($purchaseOrderProduct);
            // set the owning side to null (unless already changed)
            if ($purchaseOrderProduct->getProducts() === $this) {
                $purchaseOrderProduct->setProducts(null);
            }
        }

        return $this;
    }



}

src/Entity/Review.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Mime\Message;
use App\Repository\ReviewRepository;

/**
 * @ORM\Entity(repositoryClass=ReviewRepository::class)
 */
class Review
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\PositiveOrZero(message="Votre note doit être au dessus de 0")
     */
    private $note;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reviews")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="reviews")
     */
    private $product;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(?int $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Review;
use App\Entity\Picture;
use App\Entity\Product;
use App\Data\SearchData;
use App\Form\ReviewType;
use App\Form\SearchType;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use App\Repository\UserRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProductController extends AbstractController
{
    /**
     * @Route("/liste_produit", name="product_list")
     */
    public function productList(ProductRepository $repository, Request $request)
    {

        // On initialise les données
        $data = new SearchData();
        //on definit page et on recupère dans la requete la valeur qui correspond à page et si non defini elle est égal à 1
        $data->page = $request->get('page', 1);
        // On créé un formulaire qui utilise la class SearchType
        $form = $this->createForm(SearchType::class, $data);
        // Une fois le fomulaire construit on gère la requête qu'on passe en premier paramètre
        $form->handleRequest($request);

        //On recupère les valeurs min et max et on envoie en paramètre la recherche 
        [$min, $max] = $repository->findMinMax($data);
        //On recupère l'ensemble des produits lié à une recherche  et on lui envoie les données
        // $products = $repository->getBetterNote();
        $products  = $repository->findSearch($data);
        // Si on est dans le carde d'un requête ajax on return une reponse en json
        if ($request->get('ajax')) {
            // sleep(1); allonge le temps de reponse 
            return new JsonResponse([
                'content' => $this->renderView('product/_products.html.twig', ['products' => $products]),
                'sorting' => $this->renderView('product/_sorting.html.twig', ['products' => $products]),
                'pagination' => $this->renderView('product/_pagination.html.twig', ['products' => $products]),
                'pages' => ceil($products->getTotalItemCount() / $products->getItemNumberPerPage()),
                'min' => $min,
                'max' => $max
            ]);
        }
        return $this->render('product/list.html.twig', [
            'products' => $products,
            // 'review'=> $review,
            'form' => $form->createView(),
            'min' => $min,
            'max' => $max
        ]);
    }



    /**
     *
     * @Route("/search/bar", name="ajax_search")
     * @Method("GET")
     */
    public function searchAction(Request $request)
    {


        $requestString = $request->get('q');

        $entities = $this
            ->getDoctrine()
            ->getRepository(Product::class)
            ->findEntitiesByString($requestString);



        if (!$entities) {
            $result['entities']['error'] = "Aucun produit trouvé";
        } else {
            $result['entities'] =    $this->getRealEntities($entities);
        }

        $response = new JsonResponse(array_unique($result));

        return  $response;
    }

    public function getRealEntities($entities)
    {

        foreach ($entities as $entity) {
            $realEntities[$entity->getId()] = $entity->getLabel();
        }

        return array_unique($realEntities);
    }


    /**
     * @Route("/Produit/{id}", name="product_show")
     * 
     */

    public function showProduct(Product $product, Request $request): Response
    {

        if (!$product) {
            throw $this->createNotFoundException("Le produit recherché n'existe pas");
        }

        //On instancie l'entité Commentaires
        $reviews = new Review();
        $user = $this->getUser();

        //On crée l'objet form
        $form = $this->createForm(ReviewType::class, $reviews);


        //On récupère les données saisies
        $form->handleRequest($request);

        //On verifie si le formulaire a été envoyé et si les données sont valides
        if ($form->isSubmitted() && $form->isValid()) {
            //Le formulaire a été envoyé et les données sont valides

            $reviews->setProduct($product);
            $reviews->setUser($user);

            $reviews->setCreatedAt(new \DateTime('now'));

            //On instancie Doctrine
            $doctrine = $this->getDoctrine()->getManager();

            //On hydrate $reviews
            $doctrine->persist($reviews);

            //On écrit dans la bdd
            $doctrine->flush();
            $this->addFlash('success', "Votre commentaire a bien été pris en compte !");
        }
        return $this->render('product/show.html.twig', [
            'product' => $product,
            'formReviews' => $form->createView()
        ]);

        return $this->redirectToRoute('product_show');
    }


    /**
     * @Route("/Produit/commentaire/{id}/delete" , name="review_remove" )
     * 
     */

    public function deleteReview(Review $review = null,UserRepository $user, ManagerRegistry $managerRegistry)
    {

        $id = $review->getProduct()->getId();
        $user = $this->getUser();

        if($user === $review->getUser()){
        $Entitymanager = $managerRegistry->getManager();
        $Entitymanager->remove($review);
        $Entitymanager->flush();
        $this->addFlash( 'success', "Commentaire supprimé" );
        } else {
            $this->addFlash( 'danger', "Vous ne pouvez supprimer que vos commentaires !!!!" );
        }


        return $this->redirect($this->generateUrl('product_show', array('id' => $id )));
    }





    // public function getProductWithNote
}


												
																					        

templates/product/_pagination.html.twig
{{ knp_pagination_render(products) }}

templates/product/_products.html.twig
{# On rend un Json qui contient des chaines de caractères html #}
{% for product in products %}
{# On envoie seulement la liste les produits #}
	{% include 'product/_card.html.twig' with {product: product} only %}
{% endfor %}

templates/product/show.html.twig
{% extends 'base_without_search.html.twig' %}

{% block title %}{% endblock %}
{% block contenu %}
<style>
.carousel-inner .carousel-item-right.active,
.carousel-inner .carousel-item-next {
    transform: translateX(100%);
}

.carousel-inner .carousel-item-left.active,
.carousel-inner .carousel-item-prev {
    transform: translateX(-100%);
}
</style>
<div class="show">
	<div class="img">
		{% if product.pictures | length > 0 or product.pictures is null %}
			<div id="carousel" class="carousel slide" data-ride="carousel">
				<ol class="carousel-indicators">
					{% for pic in product.pictures  %}
						<li data-target="#carousel" data-slide-to="{{ loop.index0 }}" {% if loop.index0 == 0 %} class="active" {% endif %}></li>
					{% endfor %}
				</ol>
				<div class="carousel-inner">
					{% for pic in product.pictures  %}
						<div {% if loop.index0 == 0 %} class="carousel-item active" {% else %} class="carousel-item" {% endif %}>

							<img class="d-block w-100" src="/img/{{ pic.link }}" alt="Card image cap">
						</div>
					{% endfor %}
				</div>
				<a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		{% else %}
			<img class="card-img-top" src="https://img.pixers.pics/pho_wat(s3:700/FO/20/02/61/90/6/700_FO200261906_baee67509f735343b904be81216032dd.jpg,700,700,cms:2018/10/5bd1b6b8d04b8_220x50-watermark.png,over,480,650,jpg)/papiers-peints-licorne-mignon-avec-des-lunettes-de-soleil.jpg.jpg" alt="Card image cap">
		{% endif %}
		{# <h2>Note ({{ product.note / product.note|length }}) </h2> #}
	</div>
	<div class="resume">
		<h1>{{product.label }}</h1>
		<div class="bouton">
			<a class="btn btn-info" href="{{ path('product_list')}}">Retour à la liste</a>
			{% if  app.user and is_granted('ROLE_ADMIN') %}
				<a class="btn btn-warning" href="{{ path('admin_product_show' , {'id':product.id}) }}">Voir en mode Admin</a>
			{% endif %}
		</div>
		<h4>Description:</h4>
		<p>{{ product.description }}</p>
		<div>
			<h4>Concepteur:</h4>
			<p>{{ product.conceptor }}</p>
			<h4>Categorie:</h4>
			<p>{{ product.category }}</p>
			{% if product.genres is not null %}
				<h4>Genres</h4>
				{% for g in product.genres %}
					<em class="text muted text-primay text-italic">#{{ g.label }}</em>
				{% endfor %}
			{% endif %}
			{% if product.platforms is not null %}
				<h4>Plateformes</h4>
				{% for p in product.platforms %}
					<em class="text muted text-primay text-italic">#{{ p.label }}</em>
				{% endfor %}
			{% endif %}
		</div>
		<h4>Date de sortie :</h4>
		<p>{{ product.releaseDate |  date('d/m/Y')  }}</p>
		<h4>En stock :</h4>
		{% if  product.stock <= 0 %}
			<p>produit non disponible , nous ne savons pas si/quand il sera reapprovisioné
			</p>
		{% else %}
			<p>{{ product.stock}}</p>
		{% endif %}
		<h4>Prix :</h4>
		{% if  product.stock <= 0 %}
			<p>
				/
			</p>
		{% else %}
			<p>{{ product.price }}€</p>
		{% endif %}
		<h4>Etat :</h4>
		{% if  product.new %}
			<td scope="row">Neuf</td>
		{% else %}
			<td scope="row">Occasion</td>
		{% endif %}
		<h4>Notes des clients:</h4>
		<div class="col">
			{% include 'product/note.html.twig' with {'note': product.avgNote} %}
			({{  product.avgNote|round(1,'common') }}/5)
			<small>(Calculée sur
				{{ product.reviews|length }}
				avis)</small>
		</div>
		{# <form action="{{ path('cart_add' , {'id': product.id}) }}" method="GET">
					<select name="qty" class="span1">
					{% for i in 1..product.stock %}
					<option value="{{ i }}">{{ i }}</option>
					{% endfor %}
					</select>
				{% if date() < date(product.releaseDate) %}
					<button type="submit" class="btn btn-primary">Précommander</button>
				{% else %}
					<button type="submit" class="btn btn-primary">Ajouter au panier</button>
				{% endif %}
				</form> #}
		{% if  product.stock <= 0 %}
			<h3>
				<em>Indisponible</em>
			</h3>
		{% else %}
			{% if date() < date(product.releaseDate) %}
				<a href="{{ path('cart_add_show' , {'id': product.id}) }}" class="btn btn-danger">Précommander</a>
			{% else %}
				<a href="{{ path('cart_add_show' , {'id': product.id}) }}" class="btn btn-danger">Ajouter au panier</a>
			{% endif %}
		{% endif %}
	</div>
</div>
{% if  app.user %}
	{% set review = (product.reviewsFromAuthor(app.user)) %}
	{% set pop = (product.purchaseFromAuthor(app.user)) %}
{% endif %}



{# <-----------------------------------------------------------SI LE PRODUIT EST PAS ENCORE SORTI-----------------------> #}

{% if date() < date(product.releaseDate) %}
	<div class="alert alert-light" style="
		text-align: center;">
		<h2 class="alert-heading">Impossible de donner son avis sur un produit non sorti</h2>
	</div>
{# <-----------------------------------------------------------SI LE USER N'A PAS ACHETÉ LE PRODUIT-----------------------> #}
{# {% elseif app.user and pop.products.id != product.id %} #}
{% elseif app.user and pop.products.id is not defined %}
<div class="alert alert-light" style="text-align: center;">
		<h2 class="alert-heading">Vous ne pouvez pas donner un avis sur un produit que vous n'avez pas acheté</h2>
	</div>
	<h4>Avis</h4>{% for reviews in product.reviews %}
<div class="pagination-review">
<div class="panel-body">
	<ul class="list-group">
		<li class="list-group-item">
			<div class="row">
				<div class="col-xs-2 col-md-1"></div>
				<div class="col-xs-10 col-md-11">
					<div>
						<div class="mic-info">
							Par:
						{% if reviews.user is null %}
								<em>Profil supprimé</em>
							{% else %}
								{{ reviews.user }}
							{% endif %}
								le
								{{ reviews.createdAt |  date('d/m/Y')  }}
								à
								{{ reviews.createdAt |  date('H:i:s') }}</span>
						</div>
					</div>
					<div class="comment-text">
						<div>{{ reviews.comment }}</div>
						<strong>Note :
						</strong>
						{% include 'product/note.html.twig' with {'note': reviews.note } %}
					</div>
				</div>
			</div>
		</li>
			</div>
		</li>
	</ul>
</div>
</div>
</div>
{% endfor %}
{# <-----------------------------------------------------------SI LE USER A DÉJA COMMENTÉ-----------------------> #}
{% elseif app.user and review is not null %}
	<div class="container">
		<h4>Votre avis</h4>
		<div class="panel-body">
			<ul class="list-group">
				<li class="list-group-item">
					<div class="row">
						<div class="col-xs-2 col-md-1"></div>
						<div class="col-xs-10 col-md-11">
							<div>
								<div class="mic-info">

									le
									{{ review.createdAt |  date('d/m/Y')  }}
									à
									{{ review.createdAt |  date('H:i:s') }}</span>
							</div>
						</div>
						<div class="comment-text">
							<div>{{ review.comment }}</div>
							<strong>Note :
							</strong>
							{% include 'product/note.html.twig' with {'note': review.note } %}
						</div>
						<a href="{{ path('review_remove' , {'id': review.id}) }}"><p style="color: red;"> Supprimer mon commentaire</p><i class"fas fa-trash"></a>
					</div>
				</li>
			</div>
		</div>
	</li>
</li></ul><hr><h4>Avis</h4>{% for reviews in product.reviews %}
<div class="pagination-review">
<div class="panel-body">
	<ul class="list-group">
		<li class="list-group-item">
			<div class="row">
				<div class="col-xs-2 col-md-1"></div>
				<div class="col-xs-10 col-md-11">
					<div>
						<div class="mic-info">
							Par:
							{% if reviews.user is null %}
								<em>Profil supprimé</em>
							{% else %}
								{{ reviews.user }}
							{% endif %}
								le
								{{ reviews.createdAt |  date('d/m/Y')  }}
								à
								{{ reviews.createdAt |  date('H:i:s') }}</span>
						</div>
					</div>
					<div class="comment-text">
						<div>{{ reviews.comment }}</div>
						<strong>Note :
						</strong>
						{% include 'product/note.html.twig' with {'note': review.note } %}
					</div>
					<div class="review_remove"><i class"fa fas-trash"></button>
				</div>
			</div>
		</li>
			</div>
		</li>
</ul>
</div>
</div>
</div>
{% endfor %}
{% if product.reviews | length > 5 %}
<div id="pagination-container"></div>
{% endif %}
</div>
</div>{# <------------------------------------------SI LE USER EST CONNECTÉ----------------------------------> #}
{% elseif app.user %}
<div class="container">
<h2>Ajouter un avis</h2>
{{ form(formReviews ,  {'id':product.id}) }}</div>

{% for reviews in product.reviews %}
<div class="pagination_review">
<div class="panel-body">
<ul class="list-group">
	<li class="list-group-item">
		<div class="row">
			<div class="col-xs-2 col-md-1"></div>
			<div class="col-xs-10 col-md-11">
				<div>
					<div class="mic-info">
						Par:

						<span>
							{% if reviews.user is null %}
								<em>Profil supprimé</em>
							{% else %}
								{{ reviews.user }}
							{% endif %}
							le
							{{ reviews.createdAt |  date('d/m/Y')  }}
							à
							{{ reviews.createdAt |  date('H:i:s') }}</span>
					</div>
				</div>
				<div class="comment-text">
					<div>{{ reviews.comment }}</div>
					<strong>Note :
					</strong>
					{% include 'product/note.html.twig' with {'note': reviews.note } %}
				</div>
				<div class="action"></button>
			</div>
		</div>
	</li>
</div></li></ul></div></div>
</div>{% endfor %} {% if product.reviews | length > 7 %}
<div id="pagination-container"></div>
{% endif %}
</div></div></div>{# <------------------------------------------SI LE USER N'EST PAS CONNECTÉ----------------------------------> #}
{% elseif not app.user  %}
<div class="alert alert-secondary" role="alert">
<p><a href="{{ path('security_login') }}">Connectez vous</a> pour donner votre avis sur le produit !</p></div>
{% for reviews in product.reviews %}
<div class="pagination_review">
<div class="panel-body"><ul class="list-group"><li class="list-group-item"><div class="row"><div class="col-xs-2 col-md-1"></div><div class="col-xs-10 col-md-11"><div><div class="mic-info">
Par:
{% if reviews.user is null %}
<em>Profil supprimé</em>
{% else %}
{{ reviews.user }}
{% endif %}
	le
	{{ reviews.createdAt |  date('d/m/Y')  }}
	à
	{{ reviews.createdAt |  date('H:i:s') }}</span></div></div><div class="comment-text"><div>{{ reviews.comment }}</div><strong>Note :</strong>{% include 'product/note.html.twig' with {'note': reviews.note } %}</div><divclass="action"></button></div></div></li></div></li></ul></div> </div></div>
	{% endfor %}
{% if product.reviews | length > 5 %}
<div id="pagination-container"></div>
{% endif %}
	{% endif %} 
	{% endblock %}